### ISSUE TITLE
Cannot access state values in template

### ISSUE THREAD

**Issue by haikyuu** [gladejs/gladejs#16]
## What happened ?

-   I added a simple toggle logic to my template, but glade fails to compile.

## What did you do ?

```
class{
    onCreate(){
        this.state = {
            isMenuOpen: false,
        }
    }
    openMenu(){
        console.log("open")
        this.state.isMenuOpen = true;
    }
    closeMenu(){
        console.log("close")
        this.state.isMenuOpen = false;
    }
}
```
In the template `<div class=["menu", {"hidden":!state.isMenuOpen}]>`
-   I tried in a single file component and with separate js.

## Give some context

-   Mac OS catalina

## Show what you got

```
[!] (plugin gladejs) TypeError: Cannot read property 'isMenuOpen' of undefined
    at _marko_template._.t (/Users/ma/Workspace/abdellah-blog/build/index.marko:117:22)
    at renderer (/Users/ma/Workspace/abdellah-blog/node_modules/marko/src/runtime/components/renderer.js:218:5)
    at Template.renderToString (/Users/ma/Workspace/abdellah-blog/node_modules/marko/src/runtime/renderable.js:54:9)
    at /Users/ma/Workspace/abdellah-blog/node_modules/@gladejs/rollup/dist/gladejs-rollup.js:65:47
    at Array.forEach (<anonymous>)
    at Object.generateBundle (/Users/ma/Workspace/abdellah-blog/node_modules/@gladejs/rollup/dist/gladejs-rollup.js:51:18)
    at /Users/ma/Workspace/abdellah-blog/node_modules/rollup/dist/shared/rollup.js:18988:25
```

**Comment by AurelienStebe** [comment]
As I said on Discord, I can't seem to reproduce (just tried again), sorry.
By literally copy/pasting your code, I get :  `SyntaxError: Unable to find entry point for custom tag <class{... `
because of the missing space between "class" and the curly brace (which actually surprised me, but the Marko plugin auto-formats for me in VSCode).

Can you check your exact version of Marko in "node_modules", there has been quite a few releases of Marko lately.
Then, I think we'll ask Dylan and the eBay guys on Discord, it seems to be an issue with the Marko `renderToString()`.

**Comment by haikyuu** [comment]
Marko: 5.1.11

Here is a reproduction repo https://github.com/haikyuu/marko-blog

**Comment by AurelienStebe** [comment]
I can see why you'd think that `index.js` is a special file (it is in all other frameworks), but not in GladeJS. :)
If you're trying to do a Marko multi-file component, you need a `component.js`.
https://markojs.com/docs/class-components/#multi-file-components

Then, you might get this error `'default' is not exported by build/component.js, imported by ...`, depending on your module format and NodeJS version. It means that the JS file needs to go through Rollup's CommonJS plugin, so you can just comment out the `include` filter in your Rollup config file :

```
  commonjs({
//    include: /node_modules/, // let's _NOT_ limit this to NodeJS
    extensions: [".cjs", ".js"], // and only CommonJS files
  }),
```

**Comment by haikyuu** [comment]
Thanks for the tip. But:
- I get the same error with single file component
- I get the same error after using `component.js` and adding `module.exports` with and without the change in `rollup.config.js`

**Comment by AurelienStebe** [comment]
I just sent you a PR with my modifs : https://github.com/haikyuu/marko-blog/pull/1
Tell me if that works for you.

**Comment by haikyuu** [comment]
Thanks @AurelienStebe compilation works now.

But I get the following issue in the console 
```
(index):40 Uncaught TypeError: out.global.styles is not iterable
    at _marko_template._.renderer.t ((index):40)
    at renderer (markojs-35412373.js:4239)
    at Index.___rerender (markojs-35412373.js:3149)
    at hydrateComponentAndGetMount (markojs-35412373.js:3868)
    at markojs-35412373.js:3824
    at Array.map (<anonymous>)
    at Object.initServerRendered [as concat] (markojs-35412373.js:3816)
    at markojs-35412373.js:3747
    at Array.forEach (<anonymous>)
    at initServerRendered (markojs-35412373.js:3746)
_marko_template._.renderer.t @ (index):40
renderer @ markojs-35412373.js:4239
___rerender @ markojs-35412373.js:3149
hydrateComponentAndGetMount @ markojs-35412373.js:3868
(anonymous) @ markojs-35412373.js:3824
initServerRendered @ markojs-35412373.js:3816
(anonymous) @ markojs-35412373.js:3747
initServerRendered @ markojs-35412373.js:3746
(anonymous) @ (index):491
```
I fixed it by including the css directly but I want to know how to use Glade.js properly

**Comment by AurelienStebe** [comment]
So sorry, I thought I had already replied, just saw that I didn't. The `styles` global used to be an array, but there was just one CSS file. In any case, as you probably saw on Discord, GladeJS is going to change quite a bit when the next "`@marko/rollup`" release lands (hopefully before the end of the month). To be continued ...
